### ISSUE TITLE
comments in properties

### ISSUE THREAD

**Issue by SingingBush** [free-beer/proper-d#4]
if I have a properties file with `my.property=someValue # this end of line comment should be ignored` I'd expect that the value I end up with is simply 'someValue' but it's including the comment as well.

**Comment by free-beer** [comment]
A solid point but changing this is potentially not as straight forward as it might seem. The most basic thing to do would be to locate the earliest '#' in the line and cut that off as a comment but what if you then want to include that '#' in the value? You'd have to start getting into escaping elements or considering whether elements are contained within other elements which would take it, in my opinion, beyond the 'simple' remit I came at this from. It's an inconvenience I admit but I'm inclined to write it up as a limitation rather than make changes to accommodate it. I'll consider a pull request for it though if you have a solution.

**Comment by free-beer** [comment]
Given the lack of feedback on this one I'm going to close it out.
